name = "Tapir"
uuid = "fa01832b-62c2-42ce-ae03-728543422898"
authors = ["Valentin Churavy <v.churavy@gmail.com>"]
version = "1.11.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
